/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentProfileRouteImport } from './routes/assessment.profile'
import { Route as AssessmentGoalRouteImport } from './routes/assessment.goal'
import { Route as AssessmentCriteriaRouteImport } from './routes/assessment.criteria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentProfileRoute = AssessmentProfileRouteImport.update({
  id: '/assessment/profile',
  path: '/assessment/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentGoalRoute = AssessmentGoalRouteImport.update({
  id: '/assessment/goal',
  path: '/assessment/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentCriteriaRoute = AssessmentCriteriaRouteImport.update({
  id: '/assessment/criteria',
  path: '/assessment/criteria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment/criteria': typeof AssessmentCriteriaRoute
  '/assessment/goal': typeof AssessmentGoalRoute
  '/assessment/profile': typeof AssessmentProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment/criteria': typeof AssessmentCriteriaRoute
  '/assessment/goal': typeof AssessmentGoalRoute
  '/assessment/profile': typeof AssessmentProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment/criteria': typeof AssessmentCriteriaRoute
  '/assessment/goal': typeof AssessmentGoalRoute
  '/assessment/profile': typeof AssessmentProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment/criteria'
    | '/assessment/goal'
    | '/assessment/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assessment/criteria' | '/assessment/goal' | '/assessment/profile'
  id:
    | '__root__'
    | '/'
    | '/assessment/criteria'
    | '/assessment/goal'
    | '/assessment/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentCriteriaRoute: typeof AssessmentCriteriaRoute
  AssessmentGoalRoute: typeof AssessmentGoalRoute
  AssessmentProfileRoute: typeof AssessmentProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/profile': {
      id: '/assessment/profile'
      path: '/assessment/profile'
      fullPath: '/assessment/profile'
      preLoaderRoute: typeof AssessmentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/goal': {
      id: '/assessment/goal'
      path: '/assessment/goal'
      fullPath: '/assessment/goal'
      preLoaderRoute: typeof AssessmentGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/criteria': {
      id: '/assessment/criteria'
      path: '/assessment/criteria'
      fullPath: '/assessment/criteria'
      preLoaderRoute: typeof AssessmentCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentCriteriaRoute: AssessmentCriteriaRoute,
  AssessmentGoalRoute: AssessmentGoalRoute,
  AssessmentProfileRoute: AssessmentProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
