/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as AssessmentQuestionsRouteImport } from './routes/assessment.questions'
import { Route as AssessmentProfileRouteImport } from './routes/assessment.profile'
import { Route as AssessmentGoalRouteImport } from './routes/assessment.goal'
import { Route as AssessmentCriteriaRouteImport } from './routes/assessment.criteria'
import { Route as AssessmentAnalyzingRouteImport } from './routes/assessment.analyzing'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentQuestionsRoute = AssessmentQuestionsRouteImport.update({
  id: '/assessment/questions',
  path: '/assessment/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentProfileRoute = AssessmentProfileRouteImport.update({
  id: '/assessment/profile',
  path: '/assessment/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentGoalRoute = AssessmentGoalRouteImport.update({
  id: '/assessment/goal',
  path: '/assessment/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentCriteriaRoute = AssessmentCriteriaRouteImport.update({
  id: '/assessment/criteria',
  path: '/assessment/criteria',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentAnalyzingRoute = AssessmentAnalyzingRouteImport.update({
  id: '/assessment/analyzing',
  path: '/assessment/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/assessment/analyzing': typeof AssessmentAnalyzingRoute
  '/assessment/criteria': typeof AssessmentCriteriaRoute
  '/assessment/goal': typeof AssessmentGoalRoute
  '/assessment/profile': typeof AssessmentProfileRoute
  '/assessment/questions': typeof AssessmentQuestionsRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/assessment/analyzing': typeof AssessmentAnalyzingRoute
  '/assessment/criteria': typeof AssessmentCriteriaRoute
  '/assessment/goal': typeof AssessmentGoalRoute
  '/assessment/profile': typeof AssessmentProfileRoute
  '/assessment/questions': typeof AssessmentQuestionsRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/assessment/analyzing': typeof AssessmentAnalyzingRoute
  '/assessment/criteria': typeof AssessmentCriteriaRoute
  '/assessment/goal': typeof AssessmentGoalRoute
  '/assessment/profile': typeof AssessmentProfileRoute
  '/assessment/questions': typeof AssessmentQuestionsRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/assessment/analyzing'
    | '/assessment/criteria'
    | '/assessment/goal'
    | '/assessment/profile'
    | '/assessment/questions'
    | '/report/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/assessment/analyzing'
    | '/assessment/criteria'
    | '/assessment/goal'
    | '/assessment/profile'
    | '/assessment/questions'
    | '/report/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/assessment/analyzing'
    | '/assessment/criteria'
    | '/assessment/goal'
    | '/assessment/profile'
    | '/assessment/questions'
    | '/report/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  AssessmentAnalyzingRoute: typeof AssessmentAnalyzingRoute
  AssessmentCriteriaRoute: typeof AssessmentCriteriaRoute
  AssessmentGoalRoute: typeof AssessmentGoalRoute
  AssessmentProfileRoute: typeof AssessmentProfileRoute
  AssessmentQuestionsRoute: typeof AssessmentQuestionsRoute
  ReportIdRoute: typeof ReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/questions': {
      id: '/assessment/questions'
      path: '/assessment/questions'
      fullPath: '/assessment/questions'
      preLoaderRoute: typeof AssessmentQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/profile': {
      id: '/assessment/profile'
      path: '/assessment/profile'
      fullPath: '/assessment/profile'
      preLoaderRoute: typeof AssessmentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/goal': {
      id: '/assessment/goal'
      path: '/assessment/goal'
      fullPath: '/assessment/goal'
      preLoaderRoute: typeof AssessmentGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/criteria': {
      id: '/assessment/criteria'
      path: '/assessment/criteria'
      fullPath: '/assessment/criteria'
      preLoaderRoute: typeof AssessmentCriteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/analyzing': {
      id: '/assessment/analyzing'
      path: '/assessment/analyzing'
      fullPath: '/assessment/analyzing'
      preLoaderRoute: typeof AssessmentAnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  AssessmentAnalyzingRoute: AssessmentAnalyzingRoute,
  AssessmentCriteriaRoute: AssessmentCriteriaRoute,
  AssessmentGoalRoute: AssessmentGoalRoute,
  AssessmentProfileRoute: AssessmentProfileRoute,
  AssessmentQuestionsRoute: AssessmentQuestionsRoute,
  ReportIdRoute: ReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
